//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.30 at 11:47:41 AM EEST 
//


package trohalska.xml.xmlParserDemo.src.main.java.com.epam.training.xmldemo.entity.order;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import trohalska.xml.xmlParserDemo.src.main.java.com.epam.training.xmldemo.entity.Entity;


/**
 * &lt;p&gt;Java class for Delivery complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="Delivery"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{http://training.epam.com/xmldemo/entity}Entity"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}token"/&amp;gt;
 *         &amp;lt;choice&amp;gt;
 *           &amp;lt;sequence&amp;gt;
 *             &amp;lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&amp;gt;
 *           &amp;lt;/sequence&amp;gt;
 *           &amp;lt;sequence&amp;gt;
 *             &amp;lt;element name="phone" minOccurs="0"&amp;gt;
 *               &amp;lt;simpleType&amp;gt;
 *                 &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString"&amp;gt;
 *                   &amp;lt;pattern value="\+\d{12}"/&amp;gt;
 *                 &amp;lt;/restriction&amp;gt;
 *               &amp;lt;/simpleType&amp;gt;
 *             &amp;lt;/element&amp;gt;
 *           &amp;lt;/sequence&amp;gt;
 *         &amp;lt;/choice&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Delivery", propOrder = {
    "country",
    "address",
    "phone"
})
public class Delivery
    extends Entity
{

    @XmlElement(required = true, nillable = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String country;
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String address;
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String phone;

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

}
