//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.30 at 11:47:41 AM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://training.epam.com/xmldemo/entity/order", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package trohalska.xml.xmlParserDemo.src.main.java.com.epam.training.xmldemo.entity.order;
